# Generated by Django 2.0.7 on 2021-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210918_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtracker',
            name='typeofMeal',
            field=models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('snack', 'SNACK')], default='breakfast', max_length=20),
        ),
    ]
