"""
Django settings for HStracker project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# Base_Dir will tell us what the base directory is. You can use the print function
# to see it properly in your system
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e8sv=o@xh-hs3m=xyad)+0jmw_u0oqjsp7=gngc)&+vs+1)3cw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # '*' Allows all hosts
# [‘localhost’] or [‘localhost’, ‘iot.dorbae.kr’, ‘10.12.33.55’] : Allow specific hosts


# Application definition
# python manage.py makemmigrations
# python manage.py migrate
# Run these commands over and over again!!!!

# Django comes with built in apps that have specific functionalities
# You can see the Built in Apps and their functionalites under Lib//Django/Contrib/Auth/models.py 
# (!!!for example!!! )
# Each of these applications has something similar/identical to file models.py
# In other words, this is an example of a Built-in Model that Django has
# In thhe migrations folder, you can find out the history of the Database and how it has changed.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', # contains the core of the authentication framework and its default models
    'django.contrib.contenttypes', #allows permissions to be associated with models you create
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party Apps:
    'crispy_forms',
    # 'register.apps.RegisterConfig', #allows User Registration

    # My Apps (Apps that I have added to the project):
    # (When you create a Model.py in an App, make sure that the App is inside of the Installed Apps)
    'pages',
    'accounts',
    
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', #Manages sessions across requests
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', #Associates users with requests using sessions.
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HStracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")], # This will tell Django where to look for the Templates Folder
         # Since this is a list, more items can be added to it. Django will look through them in a top to bottom order
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HStracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'), # This is where you  define which database you will be using
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = '/' # This is where the User is being redirected once he logs in
LOGOUT_REDIRECT_URL = '' # This is where the User is being redirected once he logs out